"use client";

import Link from "next/link";
import Recommendations from "@/components/recommendations";
import { useState } from "react";
import { useQuery } from "@tanstack/react-query";
import { ArrowUpRight, Search, SlidersHorizontal, Sparkles } from "lucide-react";
import { api, type Page, type UserPublic } from "@/lib/api";
import { useCommand } from "@/lib/hooks";
import { AuthGate, Badge, Empty, ErrorMessage, Field, PageHeading } from "@/components/ui";

type Filters = { university_ids: string[]; department?: string; enrollment_status?: string | null; company?: string; role?: string; skill_tag_ids?: string[]; role_tag_ids?: string[]; interest_tag_ids?: string[]; project_available?: boolean | null; coffee_chat_available?: boolean | null; hours_per_week_min?: number | null; learning_stage?: string; activity_goal?: string; collaboration_mode?: string | null };
type SearchBody = { purpose: string; match_direction: string; filters: Filters };
type Choice = { id: string; name: string; kind?: string };

function MultiChoice({ label, choices, selected, onChange }: { label: string; choices: Choice[]; selected: string[]; onChange: (ids: string[]) => void }) {
  return <fieldset className="choice-fieldset"><legend>{label}</legend><div className="filter-tags">{choices.map(x => <label key={x.id}><input type="checkbox" checked={selected.includes(x.id)} onChange={e => onChange(e.target.checked ? [...selected, x.id] : selected.filter(id => id !== x.id))} />{x.name}</label>)}{choices.length === 0 && <span className="muted">등록된 선택지가 없어요.</span>}</div></fieldset>;
}

function Content() {
  const choices = useQuery({ queryKey: ["search-filters"], queryFn: () => api<{ universities: Choice[]; tags: Choice[] }>("/search/filters") });
  const [body, setBody] = useState<SearchBody>({ purpose: "coffee_chat", match_direction: "similar", filters: { university_ids: [], coffee_chat_available: true } });
  const [query, setQuery] = useState("");
  const search = useCommand<Page<{ user: UserPublic; reason: string }>>();
  const interpret = useCommand<SearchBody>();
  const [interpreted, setInterpreted] = useState(false);
  const [expanded, setExpanded] = useState(false);
  const setFilter = (key: keyof Filters, value: unknown) => setBody(current => ({ ...current, filters: { ...current.filters, [key]: value } }));
  return <>
    <div className="tabs explore-purpose" aria-label="탐색 목적">{[["coffee_chat", "커피챗"], ["team_building", "팀빌딩"], ["beginner_team_building", "처음 시작"]].map(([value, label]) => <button key={value} className={body.purpose === value ? "selected" : ""} aria-pressed={body.purpose === value} onClick={() => setBody({ ...body, purpose: value, match_direction: value === "coffee_chat" ? "similar" : "complementary", filters: { ...body.filters, coffee_chat_available: value === "coffee_chat" ? true : null, project_available: value !== "coffee_chat" ? true : null } })}>{label}</button>)}</div>
    <section className="panel search-panel"><div className="subheading"><h2>어떤 동문을 만나고 싶나요?</h2><Sparkles size={19} /></div><div className="search-natural"><div className="search-input"><Search size={18} /><input aria-label="찾고 싶은 동문" value={query} maxLength={3000} placeholder="직무 · 회사 · 관심 있는 기술" onChange={e => setQuery(e.target.value)} /></div><button className="icon-button filter-trigger" aria-label="상세 조건" aria-expanded={expanded} aria-controls="search-filter-fields" onClick={() => setExpanded(!expanded)}><SlidersHorizontal size={20} /></button></div><div className="search-help"><p>원하는 동문을 문장으로 설명해도 좋아요.</p><button className="text-link" disabled={interpret.isPending || !query} onClick={() => interpret.mutate({ path: "/search/interpret", body: { text: query, purpose: body.purpose } }, { onSuccess: result => { setBody(result); setInterpreted(true); setExpanded(true); } })}><Sparkles size={14} /> {interpret.isPending ? "정리 중…" : "AI로 조건 정리"}</button></div><ErrorMessage error={interpret.error} />{interpreted && <p className="notice info">아래 조건을 확인하고 수정한 뒤 동문 찾기를 눌러주세요.</p>}
      <form onSubmit={e => { e.preventDefault(); search.mutate({ path: "/search/users", body }); }}>
        <div className="quick-filters"><button type="button" aria-pressed={body.filters.coffee_chat_available === true} onClick={() => setFilter("coffee_chat_available", body.filters.coffee_chat_available === true ? null : true)}>커피챗 가능</button><button type="button" aria-pressed={body.filters.project_available === true} onClick={() => setFilter("project_available", body.filters.project_available === true ? null : true)}>프로젝트 가능</button><button type="button" onClick={() => setExpanded(!expanded)} aria-expanded={expanded}>조건 {expanded ? "접기" : "더 보기"}</button></div>
        <div id="search-filter-fields" hidden={!expanded} className="search-filter-fields">
          <MultiChoice label="학교 · 복수 선택 가능" choices={choices.data?.universities || []} selected={body.filters.university_ids} onChange={ids => setFilter("university_ids", ids)} />
          <div className="form-grid"><Field label="학적 상태"><select value={body.filters.enrollment_status || ""} onChange={e => setFilter("enrollment_status", e.target.value || null)}><option value="">전체</option><option value="student">재학</option><option value="graduate">졸업</option><option value="leave">휴학</option><option value="other">기타</option></select></Field><Field label="학과"><input value={body.filters.department || ""} onChange={e => setFilter("department", e.target.value)} /></Field><Field label="회사"><input value={body.filters.company || ""} onChange={e => setFilter("company", e.target.value)} /></Field><Field label="직무"><input value={body.filters.role || ""} onChange={e => setFilter("role", e.target.value)} /></Field><Field label="주당 최소 활동 시간"><input type="number" min={0} max={168} value={body.filters.hours_per_week_min ?? ""} onChange={e => setFilter("hours_per_week_min", e.target.value ? Number(e.target.value) : null)} /></Field><Field label="학습 단계"><select value={body.filters.learning_stage || ""} onChange={e => setFilter("learning_stage", e.target.value)}><option value="">전체</option><option value="exploring">탐색 중</option><option value="starting">처음 시작</option><option value="learning">기초 학습</option><option value="building">작은 기능 구현</option><option value="experienced">프로젝트 경험</option></select></Field><Field label="활동 목표"><input value={body.filters.activity_goal || ""} onChange={e => setFilter("activity_goal", e.target.value)} /></Field><Field label="협업 방식"><select value={body.filters.collaboration_mode || ""} onChange={e => setFilter("collaboration_mode", e.target.value || null)}><option value="">전체</option><option value="online">온라인</option><option value="offline">오프라인</option><option value="hybrid">온·오프라인</option><option value="flexible">협의 가능</option></select></Field><Field label="커피챗 가능 여부"><select value={body.filters.coffee_chat_available == null ? "" : String(body.filters.coffee_chat_available)} onChange={e => setFilter("coffee_chat_available", e.target.value === "" ? null : e.target.value === "true")}><option value="">전체</option><option value="true">가능</option><option value="false">현재 불가</option></select></Field><Field label="프로젝트 가능 여부"><select value={body.filters.project_available == null ? "" : String(body.filters.project_available)} onChange={e => setFilter("project_available", e.target.value === "" ? null : e.target.value === "true")}><option value="">전체</option><option value="true">가능</option><option value="false">현재 불가</option></select></Field><Field label="찾고 싶은 동료의 방향"><select value={body.match_direction} onChange={e => setBody({ ...body, match_direction: e.target.value })}><option value="similar">비슷한 관심사</option><option value="complementary">서로 보완하는 역할</option></select></Field></div>
          {([["skill", "기술", "skill_tag_ids"], ["role", "희망 역할", "role_tag_ids"], ["interest", "관심사", "interest_tag_ids"]] as const).map(([kind, label, key]) => <MultiChoice key={kind} label={label} choices={choices.data?.tags.filter(x => x.kind === kind) || []} selected={body.filters[key] || []} onChange={ids => setFilter(key, ids)} />)}
        </div>
        <div className="form-actions"><button className="button primary" disabled={search.isPending}><Search size={16} /> {search.isPending ? "찾는 중…" : "동문 찾기"}</button></div>
      </form><ErrorMessage error={search.error || choices.error} />
    </section>
    {!search.data && <Recommendations />}<div className="section-title" style={{ marginTop: 27 }}><h2>새롭게 만나는 동문</h2>{search.data && <span className="muted">선택한 조건으로 탐색</span>}</div>{!search.data ? <Empty title="지금 나에게 필요한 연결을 찾아보세요" description="조건을 정하고 동문 찾기를 눌러주세요. 경험이 없어도 함께할 사람을 찾을 수 있어요." /> : search.data.items.length === 0 ? <Empty title="아직 조건에 맞는 동문이 없어요" description="학교나 기술 조건을 조금 넓혀보세요." /> : <div className="grid-3">{search.data.items.map(({ user, reason }) => <Link href={`/users/${user.id}`} key={user.id} className="panel person-card"><div className="person-header"><div className="avatar">{user.display_name.slice(0, 1)}</div><div><h3>{user.display_name}</h3><p className="muted">{user.school_affiliations[0]?.university_name || "동문"}</p></div><ArrowUpRight size={17} style={{ marginLeft: "auto" }} /></div><p className="card-description">{user.bio || "공개한 경험에서 대화의 시작을 찾아보세요."}</p><div className="card-meta">{user.tags.slice(0, 4).map(x => <Badge color="lilac" key={x.id}>{x.name}</Badge>)}</div><span className="card-link">프로필 · 커피챗 <ArrowUpRight size={15} /></span><small className="muted">{reason}</small></Link>)}</div>}
  </>;
}
export default function ExplorePage() { return <><PageHeading title="탐색" description="궁금했던 길을 걸은 선배와, 함께 걸어갈 동료를 만나요." /><AuthGate><Content /></AuthGate></>; }
