"""local_ai_settings_and_career_plans

Revision ID: a427080b2017
Revises: 537adb1424b1
"""
from alembic import op
import sqlalchemy as sa


revision = 'a427080b2017'
down_revision = '537adb1424b1'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('career_plans',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('goal', sa.String(), nullable=False),
    sa.Column('content', sa.JSON(), nullable=False),
    sa.Column('facts_revision', sa.Integer(), nullable=False),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_career_plans_user_id'), 'career_plans', ['user_id'], unique=False)
    op.create_table('user_ai_settings',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('transport', sa.String(), nullable=False),
    sa.Column('easy_model', sa.String(), nullable=False),
    sa.Column('hard_model', sa.String(), nullable=False),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id')
    )
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_ai_settings')
    op.drop_index(op.f('ix_career_plans_user_id'), table_name='career_plans')
    op.drop_table('career_plans')
    # ### end Alembic commands ###
